name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Go
      uses: actions/setup-go@v4  # Updated to v4
      with:
        go-version: '1.21'  # Specify your Go version

    - name: Install dependencies
      run: go mod tidy

    - name: Build application
      run: go build -v .

    - name: Run tests
      run: go test ./...
